export default {
  ONLINE: 'ONLINE',
  OFFLINE: 'OFFLINE',
  SINGLPLAYER: 'SINGLPLAYER',  // FIXME: singleplayer
  MULTIPLAYER: 'MULTIPLAYER',
  SCENE: 'SCENE',
  ARCADE: 'ARCADE',
  CLASSIC: 'CLASSIC',
  TWO_PLAYERS: 'TWO_PLAYERS',
  THREE_PLAYERS: 'THREE_PLAYERS',
  FOUR_PLAYERS: 'FOUR_PLAYERS',
};
