openapi: "3.0.1"

info:
  version: "0.0.1"
  title: Wave Application
host: localhost:10010
basePath: /
tags:
  - name: "user"

schemes:
  - http
  #- https

consumes:
  - application/json

produces:
  - application/json
  
paths:
  /user/signup:
    post:
      tags:
      - "user"
      summary: "Creating an account."
      description: ""
      operationId: "signupUser"
      parameters:
        - in: "body"
          name: "body"
          description: "Key user information."
          required: true
          schema:
            $ref: "#/definitions/UserExtended"
      responses:
        201:
          description: "Created"
        403:
          description: "Forbidden"
  
  /user/login:
    post:
      tags:
      - "user"
      summary: "Logging in an existing account."
      description: ""
      operationId: "loginUser"
      parameters:
        - in: "body"
          name: "body"
          description: "Extended user information."
          required: true
          schema:
            $ref: "#/definitions/UserCredentials"
      responses:
        202:
          description: "Accepted"
        403:
          description: "Forbidden"

  /user/logout:
    post:
      tags:
      - "user"
      summary: "Logout from an existing account."
      description: ""
      operationId: "logoutUser"
      responses:
        200:
          description: "OK"
        500:
          description: "Internal Server Error"
  
  /user/edit:
    post:
      tags:
      - "user"
      summary: "Editing current user's profile page."
      description: ""
      operationId: "editUser"
      parameters:
        - in: "body"
          name: "body"
          description: "More detailed user information."
          required: true
          schema:
            $ref: "#/definitions/UserExtended"
      responses:
        200:
          description: "OK"
        413:
          description: "Payload Too Large"
        500:
          description: "Internal Server Error"
    
  /user/:
    get:
      tags:
      - "user"
      summary: "Viewing current user's profile information."
      description: ""
      operationId: infoCurrentUser
      responses:
        '200':
          description: "OK"
        '500':
          description: "Internal Server Error"

  /user/:username:
    get:
      tags:
      - "user"
      summary: "Viewing selected user's profile information."
      description: ""
      operationId: "infoSelectedUser"
      responses:
        200:
          description: "OK"
        500:
          description: "Internal Server Error"

  /user/:offset/:limit:
    get:
      tags:
      - "user"
      summary: "Viewing leaderboard."
      description: ""
      operationId: "leaderboard"
      responses:
        200:
          description: "OK"
        500:
          description: "Internal Server Error"

definitions:
  UserCredentials:
    type: object 
    required:
      - "username"
      - "password"
    properties:
      username:
        type: string
        example: florence
      password:
        type: string
        example: pass123

  UserExtended:
    type: object 
    required:
      - "username"
      - "password"
      - "score"
      - "avatarSource"
    properties:
      username:
        type: string
        example: florence
      password:
        type: string
        example: pass123
      avatarSource:
        type: string
        example: <avatarSource>
