openapi: "3.0.1"

info:
  version: "0.0.1"
  title: Wave Application
host: localhost:10010
basePath: /
tags:
  - name: "user"

schemes:
  - http
  #- https

consumes:
  - application/json

produces:
  - application/json
  
paths:
  /signup:
    get:
      tags:
      - user
      summary: "Creating an account."
      description: ""
      operationId: signupUser
      consumes: 
      - "application/json"
      parameters:
        - name: body
          in: body
          description: "Key user information."
          required: true
          schema:
            $ref: "#/definitions/UserCredentials"
      responses:
        201:
          description: "Created"
        403:
          description: "Forbidden"
  
  /login:
    get:
      tags:
      - user
      summary: "Logging in an existing account."
      description: ""
      operationId: loginUser
      consumes: 
      - "application/json"
      parameters:
        - name: body
          in: body
          description: "Key user information."
          required: true
          schema:
            $ref: "#/definitions/UserCredentials"
      responses:
        202:
          description: "Accepted"
        403:
          description: "Forbidden"
  
  /me:
    get:
      tags:
      - user
      summary: "Viewing current user's profile page."
      description: ""
      operationId: meShowUser
      consumes: 
      - "application/json"
      parameters:
        - name: body
          in: body
          description: "More detailed user information."
          required: true
          schema:
            $ref: "#/definitions/UserExtended"
      responses:
        200:
          description: "OK"
        500:
          description: "Internal Server Error"

  /user:
    put:
      tags:
      - user
      summary: "Edititng current user's profile information."
      description: ""
      operationId: meEditUser
      consumes: 
      - "application/json"
      parameters:
        - name: body
          in: body
          description: "More detailed user information."
          required: true
          schema:
            $ref: "#/definitions/UserExtended"
      responses:
        202:
          description: "Accepted"
        413:
          description: "Payload Too Large"
        500:
          description: "Internal Server Error"

definitions:
  UserCredentials:
    type: object 
    required:
      - "username"
      - "password"
    properties:
      username:
        type: string
        example: florence
      password:
        type: string
        example: pass123

  UserExtended:
    type: object 
    required:
      - "username"
      - "password"
      - "score"
      - "avatarSource"
    properties:
      username:
        type: string
        example: florence
      password:
        type: string
        example: pass123
      score:
        type: int
        example: 21
      avatarSource:
        type: string
        example: <avatarSource>
